### PR TITLE
A few small enhancements...

### PR DESCRIPTION
**Pull request by dlowe**
A series of small changes which make the library (which is great, by the way!) usable for my purposes:
- fire an event for exceptions in the processing thread, so that the caller can deal with them
- deliver the :ready? promise a false value on exceptions, so that dereferencing it doesn't hang forever
- add a (quit) fn so clients can quit without killing the connection
- add simple SSL support to create-connection

### CODE REVIEW

**Comment by Raynes** [comment]
All of those things sound downright swell to me.

**Comment by dlowe** [comment]
Did you mean to close it without merging?

**Comment by Raynes** [comment]
I did not. That would have been very misleading of me.

**Comment by dlowe** [comment]
:)

**Comment by dlowe** [comment]
@Raynes could you make a new release to clojars, please?

**Comment by Raynes** [comment]
Done.

**Comment by dlowe** [comment]
Fantastic, thank you!

**Comment by devth** [comment]
How does one take advantage of this SSL support?

**Comment by Raynes** [comment]
You pass `:ssl? true` to the connect function.

**Comment by devth** [comment]
Cool thanks

**Pull request merged**
